### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by shinnn**
* I updated dependencies and devDependencies.
* I added `files` field to pckage.json to slim down the package.
* I updated image format of the badges in README from PNG to SVG.

### CODE REVIEW

**Comment by brycebaril** [comment]
Released as 1.4.1, thanks!

**Comment by shinnn** [comment]
@brycebaril No problem! Thanks for your quick reviewing and release :+1: 

By the way, how about using `^` specifiers in `dependencies`? Though this PR continued using `~`, I prefer optimistic versioning.

This module depends on through2 and xtend, whose authors are reliable I think, and I believe they keeps their modules following semver.

**Comment by brycebaril** [comment]
Generally I'm not a fan of `^` and prefer to continue to use `~` everywhere, mostly because of the peculiarities of `^` when packages are > `1.0.0`.

You're right that `through2` and `xtend` shouldn't pose any issues here, but my general policy is to use `~` everywhere.

**Comment by shinnn** [comment]
@brycebaril :+1:  It also correct.

**Pull request merged**
